openapi: '3.0.2'

info:
  version: '1.0.0'
  title: Submarine
  description: Submraine internal API - manage and track your subscriptions and free trials
  license:
    name: MIT

servers:
  - url: 'http://localhost:8000/'
    description: 'Development server'
  - url: 'https://submarineapp.space/api/v1'
    description: 'Live application'

components:
  schemas:
    Category:
      type: object
      required:
        - name
      properties:
        id:
          type: integer
          readOnly: true
        name:
          type: string

    Subscription:
      type: object
      required:
        - title
        - starts_at
        - recurrence
        - cost
      properties:
        id:
          type: integer
          readOnly: true
        title:
          type: string
        category:
          type: string
          format: url
        starts_at:
          type: string
          format: date
        ends_at:
          type: string
          format: date
          nullable: true
        recurrence:
          type: string
        trial_ends_at:
          type: string
          format: date
          nullable: true
        cost:
          type: integer
        trial_cost:
          type: integer
          nullable: true

  responses:
    BadRequest:
      description: The request was rejected due to invalid contents
    NotFound:
      description: The request was rejected as the requisite entity was not found
    Created:
      description: The entity was created successfully

paths:
  /categories/:
    get:
      description: Returns all categories available
      responses:
        '200':
          description: The category list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
  /categories/{id}/:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      description: Returns information about a specific category
      responses:
        '200':
          description: The requested category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          $ref:  '#/components/responses/NotFound'
  /subscriptions/:
    get:
      description: Returns all subscriptions for this user
      responses:
        '200':
          description: The user's subscription list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Subscription'
    post:
      description: Creates a single subscription
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Subscription'
      responses:
        '204':
          $ref:  '#/components/responses/Created'
        '400':
          $ref: '#/components/responses/BadRequest'
  /subscriptions/{id}/:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      description: Returns information about a specific subscription
      responses:
        '200':
          description: The requested subscription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Subscription'
        '404':
          $ref:  '#/components/responses/NotFound'
    # patch:
    #   description: Edits a specific subscription
    #   responses:
    #     '204':
    #       description: The subscription was edited successfully
    #     '404':
    #       $ref:  '#/components/responses/NotFound'
    # delete:
    #   description: Deletes a specific subscription
    #   responses:
    #     '204':
    #       description: The subscription was deleted successfully
    #     '404':
    #       $ref:  '#/components/responses/NotFound'
