# Generated by Django 3.1.7 on 2021-02-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hull', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_cost',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='trial_ends_at',
            field=models.DateField(null=True),
        ),
    ]
