# Generated by Django 3.1.7 on 2021-02-27 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hull', '0002_auto_20210227_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
